# Generated by Django 4.0.5 on 2022-06-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_id_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='id_driver',
            new_name='is_driver',
        ),
    ]
